### PR TITLE
3.6.0

### PR DESCRIPTION
**Pull request by jshier**
This PR updates for version 3.6.0, as well as deprecating this pod in favor of Gigya’s official one, `gigya-sdk`.

### CODE REVIEW

**Comment by tzm41** [comment]
Deprecated in favor of official one... But Gigya doesn't even update the official pod! Still spitting out 3.5.9.

**Comment by tzm41** [comment]
Jk, it spits out 3.5.6

**Comment by jshier** [comment]
As far as I can tell, 3.6.0 is still the latest version. Once it gets out of date, you should reach out to Gigya to ensure they keep the pod version in sync. Their official Pod is apparently `Gigya-iOSSDK`, though they own both that and `gigya-sdk`.

**Comment by tzm41** [comment]
`Gigya-iOSSDK` provides 3.5.6 and the other provides 3.5.9 as of now.

Last time I reached out to them asking them to fix all those compiler warnings they simply told me they won't fix those, so... I am guessing I can't really rely on the official pods in this case.

**Pull request merged**
