### PR TITLE
Declare GigyaSDK a vendored framework

### PR DESCRIPTION
**Pull request by benjamindetroch**
Declare GigyaSDKframework a vendored framework
Update deployment target to 8.0

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for this! Have you tested that it properly passes linting? If so, I can merge it the next time Gigya releases an update, as I can't update the podspec without a version bump.

**Comment by benjamindetroch** [comment]
Passed lint validation and works fine for me.

Out of curiosity: is there any harm in merging it now, apart from people not getting the update unless they empty the CocoaPods cache?

**Comment by jshier** [comment]
Sorry, I can merge it now, I just can't push to cocoapods trunk without bumping the version number, which would put it out of sync with the actual framework version.

**Comment by jshier** [comment]
@benjamindetroch If you can update this PR for the 3.5.8 changes I just merged, I can merge it as well and push out a new version. 

One other question: will this PR change how the Gigya headers are imported into projects? I seem to recall an issue like that the last time I tried to make changes like this.

**Comment by benjamindetroch** [comment]
@jshier The path to the Pod folder is still added to the FRAMEWORK_SEARCH_PATHS and HEADER_SEARCH_PATHS variables, so importing the headers should work transparently. Tested with CocoaPods 1.1.1 and 1.2.1.

Feel free to give it a try first :)

**Comment by jshier** [comment]
@benjamindetroch Thanks! This has been pushed to trunk now.

**Pull request merged**
